# Copyright (C) 2018  Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License 
# Subscription Agreement, the Intel Quartus Prime License Agreement,
# the Intel FPGA IP License Agreement, or other applicable license
# agreement, including, without limitation, that your use is for
# the sole purpose of programming logic devices manufactured by
# Intel and sold by Intel or its authorized distributors.  Please
# refer to the applicable agreement for further details.


# ***************************************************************************
# ***************************************************************************
# 
# File:		C:/Users/Usuario/Documents/RATT_repositorios/Curso_HDL/Proyectos/Subprogram_Procedure2/simulation/modelsim/Subprogram_Procedure2_dump_all_vcd_nodes.tcl
# 
# Description:	Script for ModelSim-Altera (VHDL) VCD File Dumping
# 		This script is used to direct ModelSim-Altera (VHDL) to dump
# 		all nodes in the design to a VCD output file
# 
# Usages:	C:/Users/Usuario/Documents/RATT_repositorios/Curso_HDL/Proyectos/Subprogram_Procedure2/simulation/modelsim/Subprogram_Procedure2_dump_all_vcd_nodes.tcl
# 
# Generated by:	Quartus Prime
# 		Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
# 
# Date:		Thu Apr 25 00:59:34 2024
# 
# Design:	Subprogram_Procedure2
# 
# ***************************************************************************
# ***************************************************************************

# ----------------------------------------------------------------
#
proc add_vcd_signals { hierarchy vcd_filename } {
#
# Description:	This function directs ModelSim-Altera (VHDL) to print out the
#		appropriate VCD signals, with the hierarchy level
#		prepended to each signal name
#
# ----------------------------------------------------------------

   catch { vcd add "$hierarchy/Add0_a0_combout" }
   catch { vcd add "$hierarchy/Add0_a1" }
   catch { vcd add "$hierarchy/Add0_a2_combout" }
   catch { vcd add "$hierarchy/Add0_a3" }
   catch { vcd add "$hierarchy/Add0_a4_combout" }
   catch { vcd add "$hierarchy/Add0_a5" }
   catch { vcd add "$hierarchy/Add0_a6_combout" }
   catch { vcd add "$hierarchy/Add1_a0_combout" }
   catch { vcd add "$hierarchy/Add1_a1" }
   catch { vcd add "$hierarchy/Add1_a2_combout" }
   catch { vcd add "$hierarchy/Add1_a3" }
   catch { vcd add "$hierarchy/Add1_a4_combout" }
   catch { vcd add "$hierarchy/Add1_a5" }
   catch { vcd add "$hierarchy/Add1_a6_combout" }
   catch { vcd add "$hierarchy/Add2_a0_combout" }
   catch { vcd add "$hierarchy/Add2_a1" }
   catch { vcd add "$hierarchy/Add2_a2_combout" }
   catch { vcd add "$hierarchy/Add2_a3" }
   catch { vcd add "$hierarchy/Add2_a4_combout" }
   catch { vcd add "$hierarchy/Add2_a5" }
   catch { vcd add "$hierarchy/Add2_a6_combout" }
   catch { vcd add "$hierarchy/S1_a0_a_aoutput_o" }
   catch { vcd add "$hierarchy/S1_a1_a_aoutput_o" }
   catch { vcd add "$hierarchy/S1_a2_a_aoutput_o" }
   catch { vcd add "$hierarchy/S1_a3_a_aoutput_o" }
   catch { vcd add "$hierarchy/S2_a0_a_aoutput_o" }
   catch { vcd add "$hierarchy/S2_a1_a_aoutput_o" }
   catch { vcd add "$hierarchy/S2_a2_a_aoutput_o" }
   catch { vcd add "$hierarchy/S2_a3_a_aoutput_o" }
   catch { vcd add "$hierarchy/S3_a0_a_aoutput_o" }
   catch { vcd add "$hierarchy/S3_a1_a_aoutput_o" }
   catch { vcd add "$hierarchy/S3_a2_a_aoutput_o" }
   catch { vcd add "$hierarchy/S3_a3_a_aoutput_o" }
   catch { vcd add "$hierarchy/B_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/B_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/A_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/D_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/C_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/D_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/C_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/D_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/C_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/D_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/C_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/F_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/E_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/F_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/E_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/F_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/E_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/F_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/E_a3_a_ainput_o" }
}

# ----------------------------------------------------------------
#
proc main { argv } {
#
# Description:	Main entry point to script.  Iterate over all
#		hierarchy levels specified, and direct ModelSim-Altera (VHDL)
#		to print the relevant signals under each level
#
# ----------------------------------------------------------------

   set vcd_filename "Subprogram_Procedure2.vcd"
   set hierarchy "i1"

   vcd file "$vcd_filename"
   vcd on

   add_vcd_signals $hierarchy $vcd_filename
}

main $argv
