# Copyright (C) 2018  Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License 
# Subscription Agreement, the Intel Quartus Prime License Agreement,
# the Intel FPGA IP License Agreement, or other applicable license
# agreement, including, without limitation, that your use is for
# the sole purpose of programming logic devices manufactured by
# Intel and sold by Intel or its authorized distributors.  Please
# refer to the applicable agreement for further details.


# ***************************************************************************
# ***************************************************************************
# 
# File:		C:/Users/Usuario/Documents/RATT_repositorios/Curso_HDL/Proyectos/Barrel_Shifter/simulation/modelsim/Barrel_Shifter_dump_all_vcd_nodes.tcl
# 
# Description:	Script for ModelSim-Altera (Verilog) VCD File Dumping
# 		This script is used to direct ModelSim-Altera (Verilog) to dump
# 		all nodes in the design to a VCD output file
# 
# Usages:	C:/Users/Usuario/Documents/RATT_repositorios/Curso_HDL/Proyectos/Barrel_Shifter/simulation/modelsim/Barrel_Shifter_dump_all_vcd_nodes.tcl
# 
# Generated by:	Quartus Prime
# 		Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
# 
# Date:		Wed Apr 17 17:49:05 2024
# 
# Design:	Barrel_Shifter
# 
# ***************************************************************************
# ***************************************************************************

# ----------------------------------------------------------------
#
proc add_vcd_signals { hierarchy vcd_filename } {
#
# Description:	This function directs ModelSim-Altera (Verilog) to print out the
#		appropriate VCD signals, with the hierarchy level
#		prepended to each signal name
#
# ----------------------------------------------------------------

   catch { vcd add "$hierarchy/Mux3_a0_combout" }
   catch { vcd add "$hierarchy/Mux3_a1_combout" }
   catch { vcd add "$hierarchy/Mux3_a2_combout" }
   catch { vcd add "$hierarchy/Mux3_a3_combout" }
   catch { vcd add "$hierarchy/Mux3_a4_combout" }
   catch { vcd add "$hierarchy/Mux2_a0_combout" }
   catch { vcd add "$hierarchy/Mux2_a1_combout" }
   catch { vcd add "$hierarchy/Mux2_a2_combout" }
   catch { vcd add "$hierarchy/Mux2_a3_combout" }
   catch { vcd add "$hierarchy/Mux2_a4_combout" }
   catch { vcd add "$hierarchy/Mux1_a0_combout" }
   catch { vcd add "$hierarchy/Mux0_a0_combout" }
   catch { vcd add "$hierarchy/DataOut_a0_a_aoutput_o" }
   catch { vcd add "$hierarchy/DataOut_a1_a_aoutput_o" }
   catch { vcd add "$hierarchy/DataOut_a2_a_aoutput_o" }
   catch { vcd add "$hierarchy/DataOut_a3_a_aoutput_o" }
   catch { vcd add "$hierarchy/Shift_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/DataIn_a1_a_ainput_o" }
   catch { vcd add "$hierarchy/DataIn_a3_a_ainput_o" }
   catch { vcd add "$hierarchy/LeftRight_ainput_o" }
   catch { vcd add "$hierarchy/DataIn_a2_a_ainput_o" }
   catch { vcd add "$hierarchy/DataIn_a0_a_ainput_o" }
   catch { vcd add "$hierarchy/Shift_a1_a_ainput_o" }
}

# ----------------------------------------------------------------
#
proc main { argv } {
#
# Description:	Main entry point to script.  Iterate over all
#		hierarchy levels specified, and direct ModelSim-Altera (Verilog)
#		to print the relevant signals under each level
#
# ----------------------------------------------------------------

   set vcd_filename "Barrel_Shifter.vcd"
   set hierarchy "i1"

   vcd file "$vcd_filename"
   vcd on

   add_vcd_signals $hierarchy $vcd_filename
}

main $argv
